### ISSUE TITLE
Error: Could not find block-relay/contracts/BlockRelayProxy.sol from any sources; imported from witnet-ethereum-bridge/contracts/WitnetBridgeInterface.sol

### ISSUE THREAD

**Issue by montanaflynn** [stampery-labs/witnet-pricefeed-example#3]
I cloned the repo and ran `npm install` then `npm run compile` and got this error:

```
$ npm run compile

> witnet-truffle-box@0.1.0 compile /dev/witnet-pricefeed-example
> npm run compile-requests && npm run compile-contracts


> witnet-truffle-box@0.1.0 compile-requests /dev/witnet-pricefeed-example
> npx rad2sol


Compiling your Witnet requests...
=================================
> Compiling ./requests/BitcoinPrice.js
  - The result type of the request is Float

> All requests compiled successfully


Generating automatic migrations for your contracts...
=====================================================
> PriceFeed: reusing existing constructor arguments (WitnetBridgeInterface.address)

> All migrations written successfully (please remember to manually customize them if necessary).


> witnet-truffle-box@0.1.0 compile-contracts /dev/witnet-pricefeed-example
> npx truffle compile


Compiling your contracts...
===========================
Error: Could not find block-relay/contracts/BlockRelayProxy.sol from any sources; imported from witnet-ethereum-bridge/contracts/WitnetBridgeInterface.sol
    at /dev/witnet-pricefeed-example/node_modules/truffle/build/webpack:/packages/resolver/index.js:71:1
    at /dev/witnet-pricefeed-example/node_modules/truffle/build/webpack:/node_modules/async/internal/onlyOnce.js:12:1
    at next (/dev/witnet-pricefeed-example/node_modules/truffle/build/webpack:/node_modules/async/whilst.js:68:1)
    at source.resolve.then.result (/dev/witnet-pricefeed-example/node_modules/truffle/build/webpack:/packages/resolver/index.js:57:1)
Truffle v5.1.13 (core: 5.1.13)
Node v11.14.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! witnet-truffle-box@0.1.0 compile-contracts: `npx truffle compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the witnet-truffle-box@0.1.0 compile-contracts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /dev/.npm/_logs/2020-02-15T08_52_42_904Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! witnet-truffle-box@0.1.0 compile: `npm run compile-requests && npm run compile-contracts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the witnet-truffle-box@0.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /dev/.npm/_logs/2020-02-15T08_52_42_939Z-debug.log

**Comment by girazoki** [comment]
It seems npm install does not deduplicate local dependencies and thats why it gives the compilation error. As a quick solution, we are using yarn most of the times, which will install the block-relay dependency by default. If you run yarn install and yarn compile it should compile. In any case, we will look into a solution for this!

**Comment by aesedepece** [comment]
Hi @montanaflynn thanks for reporting this issue.

The problem was indeed that the package name in `package.json` from `witnet-block-relay` was misnamed as `witnet-ethereum-bridge`, thus creating a dependency duplicity that npm could not solve.

It is fixed now. Thanks @montanaflynn and @girazoki !!!

**Comment by aesedepece** [comment]
Please confirm that it works for you too. Deleting `package-lock.json` or `npm_modules` may be needed depending on your setup.

**Comment by montanaflynn** [comment]
@girazoki and @aesedepece thanks! I can confirm I no longer get this error when using `npm`.
